FROM eclipse-temurin:17.0.4_8-jre-alpine

LABEL maintainer="Marcel Jänicke <inpercima@gmail.com>"

RUN ln -snf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo "Europe/Berlin" > /etc/timezone
