FROM anapsix/alpine-java:8_server-jre_unlimited

LABEL maintainer="Marcel Jänicke <inpercima@gmail.com>"

RUN ln -snf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo "Europe/Berlin" > /etc/timezone
