version: "2.1"
services:
  mysql:
    command: >
      mysqld --character-set-server=utf8mb4
             --collation-server=utf8mb4_unicode_ci
             --default-authentication-plugin=mysql_native_password
             --max_allowed_packet=200M
             --lower_case_table_names=1
    container_name: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    healthcheck:
      test: /usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute 'SELECT 1;' --silent 2> /dev/null || exit 1
    image: mysql:8.0.22
    mem_limit: 1g
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - data-mysql:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOSTS=mysql
      - UPLOAD_LIMIT=200M
    image: phpmyadmin
    mem_limit: 1g
    restart: unless-stopped
    ports:
      - "${PHP_MY_ADMIN_PORT}:80"
volumes:
  data-mysql:
